# Site
name: "0xevilox"
title: "Problem Solving with Code"
description: "This blog covers programming, problem solving, DSA, and low-level system design. Explore tutorials, tips, and insights to enhance your coding skills and tackle complex challenges."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /0xevilox-blog
google_analytics: 'G-003YTXYWXQ'
mailchimp-list: 'https://follow.it/404-thoughts?leanpub'
follow-list: 'https://follow.it/404-thoughts?leanpub'
include: ["_pages"]
permalink: /:title/
email: vickypentester@gmail.com

# Authors
authors:
  Vignesh:
    name: Vignesh
    display_name: Evilox
    avatar: 'assets/images/Profile_0xevilox.png'
    email: vickypentester@gmail.com
    web: https://0xevilox.github.io/
    twitter: https://x.com/Mr__Leo__
    description: "A curious programmer exploring programming, problem solving, and code design. This blog is a place to learn, discover, and share ideas for those who love to grow."
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "#"
adsense-data-ad-slot: "#"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]